CREATE DATABASE BD_TEST;
USE BD_TEST;

CREATE TABLE USUARIO(
	ID_USUARIO int IDENTITY(1,1) NOT NULL,
	NOMBRES varchar(100) NOT NULL,
	CORREO varchar(100) NOT NULL,
	USUARIO varchar(20) NOT NULL,
	CLAVE varchar(20) NOT NULL,
	ESTADO int default 1
) 
GO

CREATE PROCEDURE GetUsers
AS
BEGIN 
	SELECT ID_USUARIO, NOMBRES,CORREO, USUARIO, CLAVE, ESTADO FROM USUARIO
	WHERE ESTADO = 1
END

GO

CREATE PROCEDURE GetUser(
@ID_USUARIO INT)
AS
BEGIN 
	SELECT ID_USUARIO, NOMBRES,CORREO, USUARIO, CLAVE, ESTADO FROM USUARIO
	WHERE ID_USUARIO = @ID_USUARIO AND ESTADO = 1
END

GO

CREATE PROCEDURE RegisterUser(
    @NOMBRES NVARCHAR(255),
    @CORREO NVARCHAR(255),
    @USUARIO NVARCHAR(50),
    @CLAVE NVARCHAR(255),
	@ID_USUARIO INT OUTPUT 
)
AS
BEGIN
    
    IF EXISTS (SELECT 1 FROM USUARIO WHERE USUARIO = @USUARIO)
    BEGIN       
        RETURN;
    END
   
    INSERT INTO USUARIO (NOMBRES, CORREO, USUARIO, CLAVE)
    VALUES (@NOMBRES, @CORREO, @USUARIO, @CLAVE);
   
    SET @ID_USUARIO = SCOPE_IDENTITY();
   
END

GO


CREATE PROCEDURE UpdateUser
    @ID_USUARIO INT,
    @NOMBRES NVARCHAR(255),
    @CORREO NVARCHAR(255),
    @USUARIO NVARCHAR(50),
    @CLAVE NVARCHAR(255),
	@RESULT INT OUTPUT 
AS
BEGIN
   
    IF NOT EXISTS (SELECT 1 FROM Usuario WHERE ID_USUARIO = @ID_USUARIO)
    BEGIN 
		SET @RESULT = 0;
        RETURN @RESULT; 
    END

    
    UPDATE USUARIO
    SET NOMBRES = @NOMBRES,
        CORREO = @CORREO,
        USUARIO = @USUARIO,
        CLAVE = @CLAVE
    WHERE ID_USUARIO = @ID_USUARIO;

	SET @RESULT = 1;
    RETURN @RESULT; 
END

GO

CREATE PROCEDURE DeleteUser
    @ID_USUARIO INT,   
	@RESULT INT OUTPUT 
AS
BEGIN
    
    IF NOT EXISTS (SELECT 1 FROM Usuario WHERE ID_USUARIO = @ID_USUARIO)
    BEGIN 
		SET @RESULT = 0;
        RETURN @RESULT; 
    END

    
    UPDATE USUARIO
    SET ESTADO = 0
    WHERE ID_USUARIO = @ID_USUARIO;

	SET @RESULT = 1;
    RETURN @RESULT; 
END

GO